# Input file absolute path
vcf: ""

# Script file absolute path
vcf2phylip_path: "/path/to/vcf2phylip.py"

# PLINK prune parameters
indep_pairwise:
  window_size: 20
  step_size: 5
  r2: 0.2

# K values in ADMIXTURE
K_values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
